name: Pushes to another repository

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Test trigger
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: vtnorton/studies
          event-type: new-release
          client-payload: '{"version": "v0.0.0"}'
